### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GegoSK** [junalmeida/homeassistant-torque#7]
Hello, 
I am sorry, for asking you here, but I did not find any other option.
I am trying to connect Torque with HA, but no luck yet. Last week, I found your integration. Is this integration working? I added it to HA, but there are not sensors available. Should be Torque set up as it is mention here: https://www.home-assistant.io/integrations/torque/?

I am ready to test your integration! :)

Thank you

**Comment by junalmeida** [comment]
This is in very alpha stage, but yes, to see some sensors you should setup torque like the native integration, just using a different url to push: `/api/torque_logger` 
You will also need to have you HA instance accessible from the internet (with a ssl certificate), so your phone or car radio 3G/4G connection can make requests to this integration.

**Comment by GegoSK** [comment]
Thank you for respond. Based on your comment, I realize what was the problem. Now, original Torque platform in HA is working, but your integration did not. I changed url as you wrote and made short trip. Sensors were not updated. I will try it again today.

**Comment by junalmeida** [comment]
If still unsuccessful try to grab some logs. Thx

**Comment by GegoSK** [comment]
After many attempts, Torque accepted your link. I have selected 14 sensors in Torque. Only two sensor occured in HA - 1. speed which show some speed. And empty device_tracker. 

Log: 
```
Error adding entities for domain device_tracker with platform torque_logger
Error while setting up torque_logger platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 247, in state
    if self.latitude is not None and self.longitude is not None:
  File "/config/custom_components/torque_logger/device_tracker.py", line 93, in latitude
    return float(self._restored_state[ATTR_LATITUDE])
TypeError: float() argument must be a string or a number, not 'NoneType'
```
One big difference for now. Your sensor is permanently "visible". On the contrary, Torque platform, will "hide" sensors after a few hours without driving. So I have dashboard with many errors.

**Comment by junalmeida** [comment]
Yep, that's exactly my idea, keep sensors alive.

**Comment by junalmeida** [comment]
I will have a look on this error
